; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:uno]
platform = atmelavr
board = uno
framework = arduino
lib_deps = 
    marcoschwartz/LiquidCrystal_I2C@^1.1.4
monitor_speed = 9600
build_flags = 
    -D ARDUINO_ARCH_AVR
    -D F_CPU=16000000L

; Test environment
[env:test]
platform = native
framework = arduino
lib_deps = 
    marcoschwartz/LiquidCrystal_I2C@^1.1.4
    throwtheswitch/Unity@^2.5.2
test_ignore = test_desktop
build_flags = 
    -D UNITY_INCLUDE_DOUBLE
    -D UNIT_TEST

; Native testing environment for desktop
[env:desktop]
platform = native
test_ignore = test_embedded
lib_deps = 
    throwtheswitch/Unity@^2.5.2
build_flags = 
    -D UNITY_INCLUDE_DOUBLE
    -D UNIT_TEST
    -std=c++11
